### PR TITLE
fix: add missing RTCAN callbacks

### LINKED ISSUE #25: bug: RTCAN functions not called in CAN callbacks
### Description
RTCAN handler functions need to be called in the HAL CAN callbacks, otherwise the RTCAN service will not function at all. Refer to the usage instructions in the [RTCAN README](https://github.com/sufst/rtcan/blob/main/README.md) for how to do this.

### Expected Behaviour
RTCAN handler functions are called in the HAL CAN callbacks.

### PR DESCRIPTION
**Pull request by rureverek**
### Changes
- Added TxMailbox, RxFifo and Error Callbacks
- Moved rtcan handler definition into app_threadx.c

### Related Issue(s)
Closes #25

### CODE REVIEW

File: src/Core/Src/app_threadx.c [hunk 1]
```diff
@@ -44,11 +45,17 @@
 /* Private variables ---------------------------------------------------------*/
 /* USER CODE BEGIN PV */
 static unpack_context_t unpack_context;
+static rtcan_handle_t rtcan;
 /* USER CODE END PV */
 
 /* Private function prototypes -----------------------------------------------*/
 /* USER CODE BEGIN PFP */
-
+void HAL_CAN_TxMailbox0CompleteCallback(CAN_HandleTypeDef* can_h);
```
Comment (t-bre) [inline src/Core/Src/app_threadx.c]: I don't think these prototypes are needed and possibly they could cause problems? The default declaration of these prototypes should already exist somewhere in the HAL CAN source. There is actually a default definition of these functions too which has the `__weak` attribute -- this means that when the linker encounters your new definition of the function, the weak definition will be overridden with your definition (which is exactly what we want).

**Review by t-bre — CHANGES_REQUESTED** [review]
One small change to remove function prototypes, but otherwise looks perfect!

**Review by t-bre — APPROVED** [review]
